version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_inventory
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # this did not work, manually created database table
      - ./docker/mysql/data:/var/lib/mysql